backend/models/Translation.php
<?php

namespace backend\models;

use Yii;
use common\models\User;

/**
 * This is the model class for table "translations".
 *
 * @property int $id
 * @property string $source
 * @property string $target
 * @property int $languageId
 * @property int $userId
 * @property string $createdAt
 * @property string $updatedAt
 */
class Translation extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'translations';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['source', 'target', 'languageId'], 'required'],
            [['languageId', 'userId'], 'integer'],
            [['createdAt', 'updatedAt', 'userId'], 'safe'],
            [['source', 'target'], 'string', 'max' => 255],
            [['source', 'languageId'], 'uniqueSource'],
            [['target', 'languageId'], 'uniqueTarget']
        ];
    }
    
    public function uniqueSource(){

        if($this->isNewRecord){

            $query = self::find()->where(['source'=>$this->source, 'languageId'=>$this->languageId])->one();

            if($query){
                return $this->addError('source', Yii::t('app','translationSourceUniqueCodeError', [
                    'source'=>$this->source
                ]));
            }

        }
    }

    public function uniqueTarget(){
        
        if(! $this->isNewRecord){

            $query = self::find()->where(['target'=>$this->target, 'languageId'=>$this->languageId])->one();

            if($query){
                return $this->addError('target', Yii::t('app','translationTargetUniqueCodeError', [
                    'target'=>$this->target
                ]));
            }
        }

    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'source' => Yii::t('app', 'translationSource'),
            'target' => Yii::t('app', 'translationTarget'),
            'languageId' => Yii::t('app', 'languageId'),
            'userId' => Yii::t('app','userName'),
            'createdAt' => Yii::t('app', 'createdAt'),
            'updatedAt' => Yii::t('app', 'updatedAt'),
        ];
    }


    public function beforeSave($insert) {

        $this->userId = Yii::$app->user->id;
        $this->createdAt = date('Y-m-d H:i:s');
        $this->updatedAt = $this->createdAt;

        return parent::beforeSave($insert);

    }

    public function getUser(){
        return $this->hasOne(User::className(), ['id' => 'userId']);
    }

    public function getLanguage(){
        return $this->hasOne(Language::className(), ['id' => 'languageId']);
    }

}

backend/controllers/TranslationsController.php
<?php

namespace backend\controllers;

use common\components\BaseController;
use backend\models\Language;
use Yii;
use backend\models\Translation;
use backend\models\TranslationSearch;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\widgets\ActiveForm;
use yii\web\ForbiddenHttpException;

/**
 * TranslationsController implements the CRUD actions for Translation model.
 */
class TranslationsController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'denyCallback' => function(){
                    throw new ForbiddenHttpException(Yii::t('app', 'forbiddenMessage')); 
                },
                'rules' => [
                    [
                        'actions' => ['create', 'view', 'index', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function($rule, $action){
                            if(Yii::$app->protect->isEnabled($action->controller->module->requestedRoute)){
                                return true;
                            }
                            return false;
                        }
                    ],
                    [
                        'actions' => ['searchtarget', 'searchsource'],
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Translation models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TranslationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Translation model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Translation model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Translation();

        $languages = Language::find()->asArray()->all();

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'saved').'!');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'languages' => $languages,
        ]);
    }

    /**
     * Updates an existing Translation model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'saved').'!');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Translation model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->setFlash('success', Yii::t('app', 'deleted').'!');
        return $this->redirect(['index']);
    }

    /**
     * Finds the Translation model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Translation the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Translation::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionSearchsource($value = null) {
		Yii::$app->response->format = Response::FORMAT_JSON;
		$response = ['results' => ['id' => '', 'text' => '']];
		if (!is_null($value)) {
			$model = Translation::find()
				->select('source as id, source as text')
				->where(['like', 'source', $value])
				->limit(10)->asArray()->all();

			$response['results'] = $model;
		}
		return $response;
    }

    public function actionSearchtarget($value = null) {
		Yii::$app->response->format = Response::FORMAT_JSON;
		$response = ['results' => ['id' => '', 'text' => '']];
		if (!is_null($value)) {
			$model = Translation::find()
				->select('target as id, target as text')
				->where(['like', 'target', $value])
				->limit(10)->asArray()->all();

			$response['results'] = $model;
		}
		return $response;
	}
}

backend/views/translations/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Translation */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="translation-form">

        <?php $form = ActiveForm::begin(); ?>
        
        <?php if($model->isNewRecord){ ?>

            <?= $form->field($model, 'source')->textInput(['maxlength' => true, 'placeholder' => $model->getAttributeLabel('source'), 'autocomplete' => 'off']) ?>

            <?= $form->field($model, 'languageId')->dropDownList(\yii\helpers\ArrayHelper::map($languages,'id','code'), ['prompt' => $model->getAttributeLabel('languageId')]) ?>

        <?php }else{ ?>

            <div class="form-group">
                <label class="control-label" for="translation-source"><?= Yii::t('app', 'translationSource') ?></label>
                <div><b><?= Html::encode($model->source) ?></b></div>
            </div>

            <div class="form-group">
                <label class="control-label" for="translation-languageId"><?= Yii::t('app', 'languageId') ?></label>
                <div><b><?= Html::encode($model->language->code) ?></b></div>
            </div>

        <?php } ?>

        <?= $form->field($model, 'target')->textInput(['maxlength' => true, 'placeholder' => $model->getAttributeLabel('target'), 'autocomplete' => 'off']) ?>

        <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'save'), ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

</div>

backend/views/translations/_search.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\TranslationSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="translation-search search-box">

    <div class="row">
        <?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
]);?>

        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <?=\common\widgets\Select2::widget([
    'form' => $form,
    'model' => $model,
    'attribute' => 'source',
    'url' => Url::to(['translations/searchsource']),
])?>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <?=\common\widgets\Select2::widget([
    'form' => $form,
    'model' => $model,
    'attribute' => 'languageId',
    'url' => Url::to(['language/search']),
])?>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <?=\common\widgets\Select2::widget([
    'form' => $form,
    'model' => $model,
    'attribute' => 'target',
    'url' => Url::to(['translations/searchtarget']),
])?>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <?=\common\widgets\Select2::widget([
    'form' => $form,
    'model' => $model,
    'attribute' => 'userId',
    'url' => Url::to(['users/search']),
])?>
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="form-group">
                <?=Html::submitButton(Yii::t('app', 'search'), ['class' => 'btn btn-primary'])?>
                <a href="<?=Url::to(['index'])?>" class="btn btn-default btn-outline-secondary"><?=Yii::t('app', 'reset')?></a>
            </div>
        </div>

        <?php ActiveForm::end();?>
    </div>

</div>

backend/views/translations/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Translation */

$this->title = Yii::t('app', 'createTranslation');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'translations'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="translation-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'languages' => $languages,
    ]) ?>

</div>

backend/views/translations/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\TranslationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'translations');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="translation-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'createTranslation'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'source',
            [
                'attribute' => 'languageId',
                'content' => function($model){
                    return $model->language->code;
                }
            ],
            'target',
            [
                'attribute' => 'userId',
                'content' => function($model){
                    return $model->user->name;
                } 
            ],
            'updatedAt',

            ['class' => 'yii\grid\ActionColumn', 'template' => '{view} {update}'],
        ],
    ]); ?>


</div>

backend/views/translations/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Translation */

$this->title = Yii::t('app', 'update'). ': ' . $model->source;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'translations'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->source, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'update');
?>
<div class="translation-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/translations/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Translation */

$this->title = $model->source;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'translations'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="translation-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'deleteConfirmationMessage'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'source',
            [
                'attribute' => 'languageId',
                'value' => function($model){
                    return $model->language->code;
                }
            ],
            'target',
            [
                'attribute' => 'userId',
                'value' => function($model){
                    return $model->user->name;
                } 
            ],
            'createdAt',
            'updatedAt',
        ],
    ]) ?>

</div>